services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "go-template:production-${APP_IMAGE_TAG:-local}"
    restart: unless-stopped
    command:
      - -config
      - /app/configs/config.production.yaml
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
    name: 1panel-network
